In [1]:
import numpy as np

def LUdecomp(A):
    LU=np.copy(A)
    n =len(A)
    for j in range(n-1):
        for i in range(j+1,n):
            LU[i][j] = LU[i][j]/LU[j][j]
            for k in range(j+1,n):
                LU[i][k] = LU[i][k] - LU[i][j]*LU[j][k]
    return LU

def LUforwardsub (L,b):
    n = len(L)
    y = np.zeros(n)
    y[0] = b[0]
    for i in range(1,n):
        y[i] = b[i]
        for j in range(i):
            y[i] = y[i] - L[i][j]*y[j]
    return y
            
def LUbackwardsub (U,y):
    n = len(U)
    x = np.zeros(n)
    x[n-1] = y[n-1]/U[n-1,n-1]
    for i in range(n-2,-1,-1):
        x[i] = y[i]
        for j in range(i+1,n):
            x[i] = x[i] - U[i][j]*x[j]
        x[i] /= U[i][i]
    return x
    
def LUsolve(LU,b):
    y = LUforwardsub(LU,b)
    x = LUbackwardsub(LU,y)
    return x
    
def LUinverse(LU):
    n = len(LU)
    e = np.zeros(n)
    I = np.zeros((n,n))
    for j in range(n):
        e[j] = 1.0
        x = LUsolve(LU,e)
        for i in range(n):
            I[i][j] = x[i]
        e[j] = 0.0
    return I

def LUdet(LU):
    n = len(LU)
    det = 1.0
    for i in range(n):
        det = det * LU[i][i]
    return det

A = np.matrix([[3.0,1.0],[1.0,5.0]])
LU = LUdecomp(A)
print(LU)
b = np.array([1.0,3.0])
print(b)
x = LUsolve(LU,b)
print(x)
IA = LUinverse(LU)
print(IA)
print(np.dot(A,IA))
print(LUdet(LU))


c = np.matrix([[1, 3, 5], 
               [2, 4, 7],
               [1, 1, 0]])
P = np.matrix([[0.0, 1.0, 0.0],
               [1.0, 0.0, 0.0],
               [0.0, 0.0, 1.0]])
LU_c = LUdecomp(P*c)
print(LU_c)

[[ 3.          1.        ]
 [ 0.33333333  4.66666667]]
[ 1.  3.]
[ 0.14285714  0.57142857]
[[ 0.35714286 -0.07142857]
 [-0.07142857  0.21428571]]
[[  1.00000000e+00   0.00000000e+00]
 [  2.77555756e-17   1.00000000e+00]]
14.0
[[ 2.   4.   7. ]
 [ 0.5  1.   1.5]
 [ 0.5 -1.  -2. ]]


In [33]:
np.linalg.norm(b)

1.7320508075688772

In [34]:
np.linalg.norm(b,np.inf)

1

In [35]:
np.linalg.norm(np.dot(A,x)-b)

1.0690449676496976

In [36]:
np.linalg.norm(np.dot(A,x)-b,np.inf)

1.7142857142857142

In [37]:
np.linalg.norm(np.dot(A,x)-b,np.inf)/np.linalg.norm(b,np.inf)

1.7142857142857142

In [38]:
range(5,2)

[]

In [39]:
x = list(range(5,-1,-1))
print(x)

[5, 4, 3, 2, 1, 0]


In [46]:
A = np.matrix([[1.0,-1.0],[1.0,0.0],[1.0,2.0]])
AtA = np.dot(np.transpose(A),A)
print(AtA)
LU = LUdecomp(AtA)
b = np.array([-1.0,1.0,1.0])
z = np.dot(np.transpose(A),b)
Atb = np.zeros(np.shape(A)[1])
for i in range(np.shape(A)[1]):
    Atb[i] = z[0,i]
print(Atb)
x = LUsolve(LU,Atb)
print(x)
print(np.dot(AtA,x))

[[ 3.  1.]
 [ 1.  5.]]
[ 1.  3.]
[ 0.14285714  0.57142857]
[[ 1.  3.]]
